services:
  backend:
    build:
      context: ./server/
    env_file:
      - ./server/.env
    networks:
      - integration
    restart: unless-stopped
  
  frontend:
    build:
      context: ./client/
    networks:
      - integration
    restart: unless-stopped

networks:
  integration:
    external: true
